name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_call:
  workflow_dispatch:

# Cancel in-progress runs for same PR/branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.3"

      - name: Install dependencies
        run: bun install

      - name: Run Biome linter
        run: bun run check

  test-typescript:
    name: Test TypeScript Library
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.3"

      - name: Install dependencies
        run: bun install

      - name: Type check
        run: bun run tsc

      - name: Run core tests
        run: bun run test:cadabra

      - name: Setup integration test database
        working-directory: packages/integration-tests
        run: bun run setup

      - name: Run integration tests
        run: bun run test:integration

      - name: Run benchmarks
        run: bun run bench
        continue-on-error: true

  all-checks-passed:
    name: All Quality Checks Passed
    runs-on: ubuntu-latest
    needs: [lint, test-typescript]
    if: always()

    steps:
      - name: Check all jobs
        run: |
          if [ "${{ needs.lint.result }}" != "success" ] || \
             [ "${{ needs.test-typescript.result }}" != "success" ]; then
            echo "❌ Some quality checks failed!"
            echo "Lint: ${{ needs.lint.result }}"
            echo "TypeScript Tests: ${{ needs.test-typescript.result }}"
            exit 1
          fi
          echo "✅ All quality checks passed!"
