name: Publish to NPM

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to publish (e.g., v1.0.0)'
        required: true

jobs:
  # Run all quality checks first
  quality-checks:
    name: Quality Checks
    uses: ./.github/workflows/ci.yml

  publish:
    name: Publish TypeScript Package
    runs-on: ubuntu-latest
    needs: quality-checks
    permissions:
      contents: read
      id-token: write # Required for NPM provenance

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag || github.ref }}

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.3"

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun run test:cadabra

      - name: Type check
        run: bun run tsc

      - name: Check NPM token is set
        run: |
          if [ -z "${{ secrets.NPM_TOKEN }}" ]; then
            echo "❌ ERROR: NPM_TOKEN secret is not set!"
            echo ""
            echo "To fix this:"
            echo "1. Go to https://github.com/${{ github.repository }}/settings/secrets/actions"
            echo "2. Click 'New repository secret'"
            echo "3. Name: NPM_TOKEN"
            echo "4. Value: Your NPM access token from https://www.npmjs.com/settings/tokens"
            echo ""
            echo "Create a 'Automation' token with 'Read and write' permissions"
            exit 1
          fi
          echo "✓ NPM_TOKEN is set"

      - name: Setup Node.js for NPM
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Build package
        working-directory: packages/cadabra
        run: |
          # Ensure package.json is ready for publishing
          bun run tsc --noEmit

      - name: Publish to NPM
        working-directory: packages/cadabra
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub release comment
        if: github.event_name == 'release'
        uses: actions/github-script@v7
        with:
          script: |
            const version = process.env.GITHUB_REF_NAME;
            github.rest.repos.createReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: context.payload.release.id,
              name: 'Published to NPM',
              label: `Published cadabra@${version} to NPM`
            });
